[package]
name = "dyn_trace_err"
version = "0.3.0"
edition = "2024"
authors = ["DomamaN202"]
description = "Dynamic errors with a stack trace."
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/Domaman202/dyn_trace_err"
repository = "https://github.com/Domaman202/dyn_trace_err"

[features]
default = ["all-trace"]
all-trace = []
my-trace = []
no-trace = []

[dependencies]